DIRECTORS = ["DIR 1", "DIR 2", "DIR 3", "DIR 4", "DIR 5", "ROGERIO", "VICENTE", "VPS", "YURI", "ESTRELA"]

ROOMS = ["AUDITÓRIO BLOCO B", "MINIAUDITÓRIO BLOCO A1", "ARENA", "CAD", "CONFERENCIA", "COPA", "HARVARD A1", "HARVARD B", "INOVAÇÃO", "SALA 27", "SALA 31", "SALA AMARELA BLOCO A1", "SALA AZUL - BLOCO A1", "SALA ROSA BLOCO A1", "SALA VERDE - BLOCO A1", "SALA VERDE A1", "SL DANIEL", "SL DIOGO", "SL FELIPE", "SL VICENTE", "SL YURI"]

CATERING_OPTIONS = ["ALMOÇO", "COFFEE", "ÁGUA COPO DESCARTÁVEL", "BOLACHA", "CAFÉ", "CARRINHO DE CAFÉ", "CHÁ", "COPOS DESCARTÁVEIS", "LEITE", "LOUÇAS", "ESTRELA", "IFOOD", "ENTREGA"]

CATEGORIES = {
    "interna": "Reuniões Internas",
    "externa": "Visitantes Externos",
    "evento": "Eventos"
}
